### ISSUE TITLE
Difference between Backup process ends and A new snapshot was taken

### ISSUE THREAD

**Issue by mat-m** [bit-team/user-callback#6]
Hello

I don't get what's the difference between `Backup process ends.` and `A new snapshot was taken.`
Does the backup process ends before or after the new snapshot was taken ?

Thanks for your lights :)

**Comment by buhtzz** [comment]
Sorry, for the late reply. Is this question still relevant for you?

Do you refere to point 2 and 3 in the [README](https://github.com/bit-team/user-callback#readme)? The numbers don't indicate an order but just a code that indicates the meaning of the "third argument" that is given to a user-callback script.

**Comment by aryoda** [comment]
Good question, the terms "backup (process)" and "snapshot" are in fact not self-explanatory!

The user-callback reasons "**(Backup) process begin**" and "**(backup) process end**" are called when BiT is checking if a new snapshot shall be created (which depends on the configured backup schedule, when the last snapshot was taken, if a snapshot may taken when "on battery"...).

See the source code: https://github.com/bit-team/backintime/blob/87775c9cd78b74862f6192c07e2781548e30d256/common/snapshots.py#L613

By contrast the user-callback reason "**new snapshot (taken)**" is called only when the back process has really taken a new snapshot.

See: https://github.com/bit-team/backintime/blob/87775c9cd78b74862f6192c07e2781548e30d256/common/snapshots.py#L720

This differentiation is required because you could call `backintime backup-job` eg. every hour in a `cron` job to check if any new snapshot could be taken (even if most of the times no snapshot is taken)...

**Comment by mat-m** [comment]
Thanks @aryoda , that's clear !
